name: CI/CD

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup Maven
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Build maven project
      run: mvn clean package  

    - name: Build & Push docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
        image: sovanseyha/devops-spring-test
        tags: seiha
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
